#spring:
#  config:
#    import: aws-parameterstore:/param/exhibition_${spring.profiles.active}/

decorator:
  datasource:
    p6spy:
      enable-logging: false

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.pp.controller
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false

